import React, { useState } from 'react';
import { GoogleGenAI } from '@google/genai';
import { FeaturePanel, TextArea, Select, ActionButton, ResultCard } from '../ui';

export const ImageGenerationPanel: React.FC = () => {
    const [prompt, setPrompt] = useState('A golden retriever wearing a superhero cape, flying through a city of clouds, digital painting.');
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [aspectRatio, setAspectRatio] = useState('1:1');

    const handleGenerate = async () => {
        if (!prompt.trim()) {
            setError('Please enter a prompt.');
            return;
        }
        setIsLoading(true);
        setError(null);
        setGeneratedImage(null);

        try {
            const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
            const response = await ai.models.generateImages({
                model: 'imagen-4.0-generate-001',
                prompt: prompt,
                config: { 
                    numberOfImages: 1, 
                    outputMimeType: 'image/jpeg',
                    aspectRatio: aspectRatio as any,
                },
            });
            const base64Image = response.generatedImages[0].image.imageBytes;
            setGeneratedImage(`data:image/jpeg;base64,${base64Image}`);
        } catch (e: any) {
            setError(`Image generation failed: ${e.message}`);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <FeaturePanel title="Image Generation" description="Create high-quality images from text descriptions using the Imagen model.">
            <TextArea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe the image you want to create..."
                rows={4}
            />
            <div className="flex items-center space-x-4">
                <label htmlFor="aspect-ratio-select" className="font-bold text-white">Aspect Ratio:</label>
                <Select id="aspect-ratio-select" value={aspectRatio} onChange={(e) => setAspectRatio(e.target.value)}>
                    {["1:1", "3:4", "4:3", "9:16", "16:9"].map(r => <option key={r} value={r}>{r}</option>)}
                </Select>
            </div>
            <ActionButton onClick={handleGenerate} isLoading={isLoading}>
                Generate Image
            </ActionButton>
            {error && <p className="text-red-500 text-center">{error}</p>}
            {generatedImage && (
                 <ResultCard title="Generated Image">
                     <img src={generatedImage} alt="Generated by AI" className="mx-auto rounded-lg border border-white/10" />
                     <a href={generatedImage} download="generated-image.jpg" className="block text-center mt-4 text-gemini-blue-light hover:underline">Download Image</a>
                 </ResultCard>
            )}
        </FeaturePanel>
    );
};
